columns:
  transaction_id: int
  customer_id: int
  device_id: int
  merchant_id: int
  timestamp: object
  amount: float
  payment_method: object
  is_international: int
  merchant_category: object
  ip_address_risk_score: float
  device_trust_score: float
  txn_count_last_24h: int
  avg_amount_last_24h: float
  merchant_diversity_last_7d: int
  device_change_flag: int
  location_change_flag: int
  authentication_method: object
  otp_success_rate_customer: float
  past_fraud_count_customer: int
  past_disputes_customer: int
  merchant_historical_fraud_rate: float
  hour_of_day: int
  day_of_week: int
  is_weekend: int
  is_fraud: int